/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.metas;

import dao.CampanhaDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.math.BigDecimal;
import javax.swing.table.DefaultTableModel;
import view.dashboard.DashboardView;

/**
 *
 * @author mathe
 */



public class MetasAdminView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MetasAdminView.class.getName());

    /**
     * Creates new form MetasAdminView
     */
    public MetasAdminView() {
        initComponents();
        carregarTabela();
        
    }
    
    private void buscarCampanhaPorId() {
        try {
            int id = Integer.parseInt(SearchCampanhaPorIdTextField.getText().trim());
            CampanhaDAO dao = new CampanhaDAO();

            try (java.sql.ResultSet rs = dao.buscarPorId(id)) {
                DefaultTableModel model = new DefaultTableModel(
                    new Object[]{"ID", "Titulo", "Descricao", "Mes Ref.", "Meta Dinheiro", "Meta Alimentos", "Meta Roupas", "Meta Brinquedos", "Meta Livros", "Meta Calcados", "Meta Eletrodomesticos", "Meta Saude", "Ativa", "Id Admin", "Criado em"},
                    0
                ) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };

                if (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("id_campanha"),
                        rs.getString("titulo"),
                        rs.getString("descricao"),
                        rs.getDate("mes_referencia"),
                        rs.getBigDecimal("meta_dinheiro"),
                        rs.getInt("meta_alimentos"),
                        rs.getInt("meta_roupas"),
                        rs.getInt("meta_brinquedos"),
                        rs.getInt("meta_livros"),
                        rs.getInt("meta_calcados"),
                        rs.getInt("meta_eletrodomesticos"),
                        rs.getInt("meta_saude"),
                        rs.getBoolean("ativa"),
                        rs.getInt("id_admin"),
                        rs.getTimestamp("criado_em")
                    });

                    jTable1.setModel(model);
                    javax.swing.JOptionPane.showMessageDialog(this, "Campanha encontrada.");
                } else {
                    jTable1.setModel(model);
                    javax.swing.JOptionPane.showMessageDialog(this, "Campanha não encontrada.");
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao buscar campanha.");
        }
    }
    
    private void limparCampos() {
        IdCampanhaTextField.setText("");
        TituloTextField.setText("");
        DescricaoTextField.setText("");
        ValorMetaTextField.setText("");
        AtivaCheckBox.setSelected(false);
        SearchCampanhaPorIdTextField.setText("");
        TipoDeMetaComboBox.setSelectedIndex(0);
    }
    
    private void carregarTabela() {
        CampanhaDAO dao = new CampanhaDAO();
        java.util.List<Object[]> lista = dao.listarMetasResumidas();

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object[]{"ID", "Titulo", "Descricao", "Tipo_Meta", "Valor_Meta", "Ativa", "Id Admin", "Criado em"},
            0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (Object[] linha : lista) {
            model.addRow(linha);
        }

        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        EditarBtn = new javax.swing.JLabel();
        ExcluirBtn = new javax.swing.JLabel();
        CriarBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        SearchCampanhaPorIdTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        IdCampanhaTextField = new javax.swing.JTextField();
        TituloTextField = new javax.swing.JTextField();
        DescricaoTextField = new javax.swing.JTextField();
        TipoDeMetaComboBox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ValorMetaTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        AtivaCheckBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 51, 0));

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard/dashboard.png"))); // NOI18N
        jLabel3.setText("Dashboard");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard/list_.png"))); // NOI18N
        jLabel4.setText("Doações");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard/pix.png"))); // NOI18N
        jLabel5.setText("Doar Pix");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard/donation.png"))); // NOI18N
        jLabel6.setText("Doar");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuarios");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Admin");

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Metas");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Beneficiarios");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel11.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Relatorios");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/200.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 227, 157), 2, true));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Descricao", "Tipo_meta", "Valor_meta", "Ativa", "Id Admin", "Criado em"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setText("Metas Atuais");

        EditarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/formIcons/edit.png"))); // NOI18N
        EditarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarBtnMouseClicked(evt);
            }
        });

        ExcluirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/formIcons/delete.png"))); // NOI18N
        ExcluirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExcluirBtnMouseClicked(evt);
            }
        });

        CriarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/criar.png"))); // NOI18N
        CriarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CriarBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CriarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExcluirBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EditarBtn)
                        .addGap(14, 14, 14))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CriarBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1))
                    .addComponent(ExcluirBtn)
                    .addComponent(EditarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 51), 2, true));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setText("Ola, fulanodetal");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard/logpppp.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        SearchCampanhaPorIdTextField.setText("Buscar Campanha ID");

        jButton2.setText("Buscar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(SearchCampanhaPorIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SearchCampanhaPorIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(9, 9, 9))
        );

        jLabel12.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel12.setText("Editar Meta");

        jLabel14.setText("ID Campanha");

        jLabel16.setText("Titulo");

        jLabel17.setText("Descrição");

        IdCampanhaTextField.setText("jTextField1");

        TituloTextField.setText("jTextField1");

        DescricaoTextField.setText("jTextField1");

        TipoDeMetaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DINHEIRO", "ALIMENTO", "ROUPA", "BRINQUEDO", "LIVRO", "CALCADO", "ELETRODOMESTICO", "SAUDE" }));

        jLabel18.setText("Tipo de Meta");

        jLabel19.setText("Valor Meta");

        ValorMetaTextField.setText("jTextField1");

        jLabel20.setText("Ativa?");

        AtivaCheckBox.setText("jCheckBox1");

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setText("Salvar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel23.setForeground(new java.awt.Color(255, 102, 102));
        jLabel23.setText("Limpar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(101, 101, 101)
                                .addComponent(jLabel16))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(IdCampanhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(TituloTextField))
                            .addComponent(DescricaoTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)
                                    .addComponent(TipoDeMetaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AtivaCheckBox))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ValorMetaTextField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdCampanhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DescricaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipoDeMetaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValorMetaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AtivaCheckBox)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))))
                .addGap(11, 11, 11))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    int linha = jTable1.getSelectedRow();

    if (linha >= 0) {
        IdCampanhaTextField.setText(jTable1.getValueAt(linha, 0).toString());
        TituloTextField.setText(jTable1.getValueAt(linha, 1).toString());
        DescricaoTextField.setText(jTable1.getValueAt(linha, 2).toString());
        TipoDeMetaComboBox.setSelectedItem(jTable1.getValueAt(linha, 3).toString());
        ValorMetaTextField.setText(jTable1.getValueAt(linha, 4).toString());
        AtivaCheckBox.setSelected(Boolean.parseBoolean(jTable1.getValueAt(linha, 12).toString()));
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void EditarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarBtnMouseClicked
        try {
            int idCampanha = Integer.parseInt(IdCampanhaTextField.getText().trim());
            String titulo = TituloTextField.getText().trim();
            String descricao = DescricaoTextField.getText().trim();
            java.sql.Date mesReferencia = java.sql.Date.valueOf("2026-06-01"); // ajuste depois se quiser pegar de um campo
            BigDecimal metaDinheiro = new BigDecimal(ValorMetaTextField.getText().trim().replace(",", "."));
            boolean ativa = AtivaCheckBox.isSelected();

            int metaAlimentos = 0;
            int metaRoupas = 0;
            int metaBrinquedos = 0;
            int metaLivros = 0;
            int metaCalcados = 0;
            int metaEletrodomesticos = 0;
            int metaSaude = 0;

            Object item = TipoDeMetaComboBox.getSelectedItem();
            String tipo = item != null ? item.toString() : "";

            if ("DINHEIRO".equalsIgnoreCase(tipo)) {
                metaDinheiro = new BigDecimal(ValorMetaTextField.getText().trim().replace(",", "."));
            } else if ("ALIMENTO".equalsIgnoreCase(tipo)) {
                metaAlimentos = Integer.parseInt(ValorMetaTextField.getText().trim());
            } else if ("ROUPA".equalsIgnoreCase(tipo)) {
                metaRoupas = Integer.parseInt(ValorMetaTextField.getText().trim());
            } else if ("BRINQUEDO".equalsIgnoreCase(tipo)) {
                metaBrinquedos = Integer.parseInt(ValorMetaTextField.getText().trim());
            } else if ("LIVRO".equalsIgnoreCase(tipo)) {
                metaLivros = Integer.parseInt(ValorMetaTextField.getText().trim());
            } else if ("CALCADO".equalsIgnoreCase(tipo)) {
                metaCalcados = Integer.parseInt(ValorMetaTextField.getText().trim());
            } else if ("ELETRODOMESTICO".equalsIgnoreCase(tipo)) {
                metaEletrodomesticos = Integer.parseInt(ValorMetaTextField.getText().trim());
            } else if ("SAUDE".equalsIgnoreCase(tipo)) {
                metaSaude = Integer.parseInt(ValorMetaTextField.getText().trim());
            }

            CampanhaDAO dao = new CampanhaDAO();
            boolean ok = dao.atualizar(idCampanha, titulo, descricao, mesReferencia, metaDinheiro,
                    metaAlimentos, metaRoupas, metaBrinquedos, metaLivros, metaCalcados,
                    metaEletrodomesticos, metaSaude, ativa);

            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this, "Campanha atualizada com sucesso!");
                carregarTabela();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao atualizar campanha.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao editar campanha.");
        }
    }//GEN-LAST:event_EditarBtnMouseClicked

    private void ExcluirBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExcluirBtnMouseClicked
        try {
            int idCampanha = Integer.parseInt(IdCampanhaTextField.getText().trim());

            int confirm = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "Deseja excluir esta campanha?",
                    "Confirmar exclusão",
                    javax.swing.JOptionPane.YES_NO_OPTION
            );

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                CampanhaDAO dao = new CampanhaDAO();
                boolean ok = dao.excluir(idCampanha);

                if (ok) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Campanha excluída com sucesso.");
                    carregarTabela();
                    limparCampos();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Erro ao excluir campanha.");
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao excluir.");
        }
    }//GEN-LAST:event_ExcluirBtnMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

    }//GEN-LAST:event_jLabel15MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int idCampanha = Integer.parseInt(IdCampanhaTextField.getText().trim());
            String titulo = TituloTextField.getText().trim();
            String descricao = DescricaoTextField.getText().trim();
            java.sql.Date mesReferencia = java.sql.Date.valueOf("2026-06-01");
            boolean ativa = AtivaCheckBox.isSelected();

            int metaAlimentos = 0;
            int metaRoupas = 0;
            int metaBrinquedos = 0;
            int metaLivros = 0;
            int metaCalcados = 0;
            int metaEletrodomesticos = 0;
            int metaSaude = 0;
            BigDecimal metaDinheiro = BigDecimal.ZERO;

            String tipo = String.valueOf(TipoDeMetaComboBox.getSelectedItem());
            String valor = ValorMetaTextField.getText().trim().replace(",", ".");

            if ("DINHEIRO".equalsIgnoreCase(tipo)) {
                metaDinheiro = new BigDecimal(valor);
            } else if ("ALIMENTO".equalsIgnoreCase(tipo)) {
                metaAlimentos = Integer.parseInt(valor);
            } else if ("ROUPA".equalsIgnoreCase(tipo)) {
                metaRoupas = Integer.parseInt(valor);
            } else if ("BRINQUEDO".equalsIgnoreCase(tipo)) {
                metaBrinquedos = Integer.parseInt(valor);
            } else if ("LIVRO".equalsIgnoreCase(tipo)) {
                metaLivros = Integer.parseInt(valor);
            } else if ("CALCADO".equalsIgnoreCase(tipo)) {
                metaCalcados = Integer.parseInt(valor);
            } else if ("ELETRODOMESTICO".equalsIgnoreCase(tipo)) {
                metaEletrodomesticos = Integer.parseInt(valor);
            } else if ("SAUDE".equalsIgnoreCase(tipo)) {
                metaSaude = Integer.parseInt(valor);
            }

            CampanhaDAO dao = new CampanhaDAO();
            boolean ok = dao.atualizar(idCampanha, titulo, descricao, mesReferencia, metaDinheiro,
                    metaAlimentos, metaRoupas, metaBrinquedos, metaLivros, metaCalcados,
                    metaEletrodomesticos, metaSaude, ativa);

            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this, "Campanha atualizada com sucesso.");
                carregarTabela();
                limparCampos();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao atualizar campanha.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar campanha.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CriarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CriarBtnMouseClicked
            MetasAdminCriarView frame = new MetasAdminCriarView();
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int x = (screenSize.width - frame.getWidth()) / 2;
            int y = (screenSize.height - frame.getHeight()) / 2;
            frame.setLocation(x, y);
            frame.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_CriarBtnMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        buscarCampanhaPorId();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MetasAdminView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AtivaCheckBox;
    private javax.swing.JLabel CriarBtn;
    private javax.swing.JTextField DescricaoTextField;
    private javax.swing.JLabel EditarBtn;
    private javax.swing.JLabel ExcluirBtn;
    private javax.swing.JTextField IdCampanhaTextField;
    private javax.swing.JTextField SearchCampanhaPorIdTextField;
    private javax.swing.JComboBox<String> TipoDeMetaComboBox;
    private javax.swing.JTextField TituloTextField;
    private javax.swing.JTextField ValorMetaTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
