/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.devtools;
import java.awt.Image;
import java.math.BigDecimal;
import java.util.Map;
import java.util.Base64;
import javax.swing.ImageIcon;
import util.PixGenerator;
/**
 *
 * @author mathe
 */
public class DevToolsView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DevToolsView.class.getName());

    /**
     * Creates new form DevToolsView
     */
    public DevToolsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PixFoda = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        CopiaEColaLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NomeField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        ValorField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PixFoda.setLabel("Pix Foda");
        PixFoda.addActionListener(this::PixFodaActionPerformed);

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setLabel("Copiar e Colar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        CopiaEColaLabel.setText("Sem pix ainda pae");

        jLabel2.setText("Imagem");

        NomeField.addActionListener(this::NomeFieldActionPerformed);
        NomeField.addPropertyChangeListener(this::NomeFieldPropertyChange);

        EmailField.addActionListener(this::EmailFieldActionPerformed);

        ValorField.addActionListener(this::ValorFieldActionPerformed);

        jLabel1.setText("Nome");

        jLabel3.setText("Email");

        jLabel4.setText("Valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CopiaEColaLabel)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(PixFoda, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ValorField)
                        .addComponent(EmailField)
                        .addComponent(NomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CopiaEColaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PixFoda, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(NomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ValorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PixFodaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        PixFoda.setEnabled(false);
        try {
            BigDecimal valor = new BigDecimal(ValorField.getText());
            String email = "lol@gmail.com";
            Map<String, String> pix = PixGenerator.gerarPix(valor, email);
            //CopiaEColaLabel.setText(pix.get("copia_cola"));
            System.out.println("Copia e Cola: " + pix.get("copia_cola"));

            byte[] decodedBytes = Base64.getDecoder().decode(pix.get("imagem_base64"));
            Image img = new ImageIcon(decodedBytes).getImage();
            Image qr = img.getScaledInstance(220, 220, Image.SCALE_SMOOTH);
            jLabel2.setIcon(new ImageIcon(qr));
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            PixFoda.setEnabled(true);
        }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed



    }//GEN-LAST:event_jButton2ActionPerformed

    private void NomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeFieldActionPerformed

    private void NomeFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_NomeFieldPropertyChange
        String nome = NomeField.getText();
    }//GEN-LAST:event_NomeFieldPropertyChange

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        String Email = EmailField.getText();
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void ValorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorFieldActionPerformed
        BigDecimal valor = new BigDecimal(ValorField.getText());
    }//GEN-LAST:event_ValorFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DevToolsView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CopiaEColaLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField NomeField;
    private javax.swing.JButton PixFoda;
    private javax.swing.JTextField ValorField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
