/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.usjt.loginandsignup;

/**
 *
 * @author mathe
 */
public class SignUp extends javax.swing.JFrame {
    

    /**
     * Creates new form Login
     */
    public SignUp() {
        initComponents();
        java.awt.Point[] origin = {null};
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent e) {
                origin[0] = e.getPoint();
            }
        });
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent e) {
                if (origin[0] != null) {
                    java.awt.Point p = getLocation();
                    setLocation(
                        p.x + e.getX() - origin[0].x,
                        p.y + e.getY() - origin[0].y
                    );
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        UsuarioInput = new javax.swing.JTextField();
        UsuarioText = new javax.swing.JLabel();
        NomeInput = new javax.swing.JTextField();
        NomeText = new javax.swing.JLabel();
        EmailText = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        telefoneInput = new javax.swing.JTextField();
        telefoneText = new javax.swing.JLabel();
        SenhaInput = new javax.swing.JPasswordField();
        SenhaTexto = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        RegistrarText = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        MinimizeButton = new javax.swing.JButton();
        MaximizeButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CloseButton1 = new javax.swing.JButton();
        NoAccountText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        Right.setBackground(new java.awt.Color(0, 102, 102));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));

        UsuarioInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsuarioInput.addActionListener(this::UsuarioInputActionPerformed);

        UsuarioText.setBackground(new java.awt.Color(153, 153, 153));
        UsuarioText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsuarioText.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioText.setText("Usuario");

        NomeInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeInput.addActionListener(this::NomeInputActionPerformed);

        NomeText.setBackground(new java.awt.Color(153, 153, 153));
        NomeText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeText.setForeground(new java.awt.Color(255, 255, 255));
        NomeText.setText("Nome");

        EmailText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailText.addActionListener(this::EmailTextActionPerformed);

        Email.setBackground(new java.awt.Color(153, 153, 153));
        Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("E-mail");

        telefoneInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefoneInput.addActionListener(this::telefoneInputActionPerformed);

        telefoneText.setBackground(new java.awt.Color(153, 153, 153));
        telefoneText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefoneText.setForeground(new java.awt.Color(255, 255, 255));
        telefoneText.setText("Telefone");

        SenhaTexto.setBackground(new java.awt.Color(153, 153, 153));
        SenhaTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SenhaTexto.setForeground(new java.awt.Color(255, 255, 255));
        SenhaTexto.setText("Senha");

        RegisterButton.setBackground(new java.awt.Color(0, 102, 102));
        RegisterButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Registrar");

        RegistrarText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        RegistrarText.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarText.setText("Registrar");

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(RegistrarText))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsuarioText)
                            .addComponent(NomeText)
                            .addComponent(Email)
                            .addComponent(telefoneText)
                            .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(UsuarioInput)
                                .addComponent(NomeInput)
                                .addComponent(SenhaTexto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SenhaInput, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EmailText)
                                .addComponent(telefoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(RegistrarText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsuarioText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsuarioInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SenhaTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SenhaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel1.add(Right);
        Right.setBounds(0, 0, 410, 500);

        Left.setBackground(new java.awt.Color(229, 231, 235));

        MinimizeButton.setBackground(new java.awt.Color(51, 255, 51));
        MinimizeButton.setText(".");
        MinimizeButton.addActionListener(this::MinimizeButtonActionPerformed);

        MaximizeButton.setBackground(new java.awt.Color(255, 255, 102));
        MaximizeButton.setText("-");
        MaximizeButton.addActionListener(this::MaximizeButtonActionPerformed);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/usjt/loginandsignup/resources/jollyroger.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Monocraft", 1, 48)); // NOI18N
        jLabel5.setText("Bem Vindo");

        jLabel8.setFont(new java.awt.Font("Monocraft", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Lorem ipsum dolor sit amet, consectetur");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel9.setFont(new java.awt.Font("Monocraft", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("elit, sed do eiusmod tempor");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        CloseButton1.setBackground(new java.awt.Color(255, 51, 51));
        CloseButton1.setText("X");
        CloseButton1.addActionListener(this::CloseButton1ActionPerformed);

        NoAccountText.setForeground(new java.awt.Color(0, 0, 153));
        NoAccountText.setText("Eu não tenho uma conta.");
        NoAccountText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clique(evt);
            }
        });

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaximizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CloseButton1)
                .addGap(288, 288, 288))
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(NoAccountText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(227, 227, 227))
            .addGroup(LeftLayout.createSequentialGroup()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaximizeButton)
                    .addComponent(MinimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CloseButton1))
                .addGap(190, 190, 190)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(51, 51, 51)
                .addComponent(NoAccountText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Left);
        Left.setBounds(410, 0, 390, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonActionPerformed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_MinimizeButtonActionPerformed

    private void MaximizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaximizeButtonActionPerformed
        
    }//GEN-LAST:event_MaximizeButtonActionPerformed

    private void telefoneInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneInputActionPerformed

    private void EmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextActionPerformed

    private void NomeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeInputActionPerformed

    private void UsuarioInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioInputActionPerformed

    private void CloseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_CloseButton1ActionPerformed

    private void Clique(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clique
        Login LoginFrame = new Login();
        LoginFrame.dispose();
        LoginFrame.setUndecorated(true);
        LoginFrame.setVisible(true);
        LoginFrame.setLocationRelativeTo(null); // centro
        LoginFrame.setResizable(false);
        LoginFrame.pack();
        this.dispose();
    }//GEN-LAST:event_Clique

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton1;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailText;
    private javax.swing.JPanel Left;
    private javax.swing.JButton MaximizeButton;
    private javax.swing.JButton MinimizeButton;
    private javax.swing.JLabel NoAccountText;
    private javax.swing.JTextField NomeInput;
    private javax.swing.JLabel NomeText;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel RegistrarText;
    private javax.swing.JPanel Right;
    private javax.swing.JPasswordField SenhaInput;
    private javax.swing.JLabel SenhaTexto;
    private javax.swing.JTextField UsuarioInput;
    private javax.swing.JLabel UsuarioText;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField telefoneInput;
    private javax.swing.JLabel telefoneText;
    // End of variables declaration//GEN-END:variables
}
